development:
  adapter: postgresql
  encoding: unicode
  database: cnab_db_development
  host: ''
  pool: 5
  username: armando
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cnab_db_test
  host: ''
  pool: 5
  username: armando
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cnab_db_production
  pool: 5
  username: armando
  password: